### ISSUE TITLE
Yellow screen of death when deploying via github

### ISSUE THREAD

**Issue by mikespub** [Azure-Samples/app-service-web-python-get-started#1]
When you fork this on Github and use that as deployment source for a brand-new Web App, the resulting website shows you a nice yellow screen of death. After some investigation, the actual error turns out to be:

Couldn't find type for class Microsoft.WindowsAzure.Diagnostics.DiagnosticMonitorTraceListener, Microsoft.WindowsAzure.Diagnostics, Version=1.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35.

Why is this part of the web.config here, and if it does bring value for diagnostics or whatever on azure, why isn't there a valid type available?

**Comment by cephalin** [comment]
I'm not able to reproduce your error. If you're talking about an HTTP 500 error, then it most likely means that you are trying to access the app before the deployment script is done.

**Comment by cephalin** [comment]
FYI, this sample was designed for a tutorial that uses local git as deployment source. If you follow that, then the git deployment will block until the server side completes the all the deployment steps. But if you try to set up GitHub deployment, then you will get a "success" message as soon as the deployments source is configured, even before the code is deployed at all.

**Comment by mikespub** [comment]
Ah, indeed that might explain this issue and issue #2 

Since the deployment process (from local git or Github) to Azure seems to happen by magic anyway, at least for people following the tutorial, perhaps it would be a good idea to mention this in the tutorial and samples?

Thanks

**Comment by cephalin** [comment]
In local git deployment (which the tutorial is about), you actually get verbose output, including when files are copied to wwwroot/static. I can add a note in the source control doc https://azure.microsoft.com/en-us/documentation/articles/web-sites-publish-source-control/ per your suggestion.

**Comment by mikespub** [comment]
So actually what you're saying is that in that article, the manual deployment from a local git will work for the sample, but the continuous deployment won't - is that it?

The reason I ended up in this mess is that I went directly to the second part, i.e. continuous deployment, simply by forking the sample on Github - without bothering to try out the manual deployment first.

So if the deployment mechanism for this sample can't deal with continuous deployment, or some additional steps are needed to verify that the deployment has actually finished, it would be good to write that down in that section (or in the Troubleshooting section).

**Comment by cephalin** [comment]
The article that this sample is written for (see README.md) does not cover continuous deployment with GitHub. But your feedback is a good caveat for the general GitHub configuration scenario so I'll add the caveat to the appropriate article.
