### ISSUE TITLE
Static files aren't being served

### ISSUE THREAD

**Issue by mikespub** [Azure-Samples/app-service-web-python-get-started#2]
When deploying this sample as is (after fixing the yellow screen of death), static files aren't being served and Django complains that it can't find ^static defined in urls.py.

**Comment by cephalin** [comment]
I also can't reproduce this error, but could get something similar IF I access the app before the deployment process finishes. If deployment hasn't copied the files to wwwroot/static yet, then I get a page without CSS/JS, and the F12 view shows that all the access to the /static/... files return 404. No complaint by Django though. That maybe some custom debugging in your setup?

In any case, after I waited until deployment finishes, I get the expected page no problem.

**Comment by mikespub** [comment]
Thanks, I'll close this one and leave it in issue #1 to adapt the documentation if possible.
