### ISSUE TITLE
Document Moved

### ISSUE THREAD

**Issue by jmwai** [Azure-Samples/app-service-web-python-get-started#4]
Hi there,
I am using Django Rest Framework on Azure App Service and my JSON comes back with this HTML added to the response. This is only for POST requests.
```
<head><title>Document Moved</title></head>
<body><h1>Object Moved</h1>This document may be found <a HREF=".......">here</a></body>

```
Any idea how I can sort this out?

**Comment by cephalin** [comment]
Unrelated to sample
