### ISSUE TITLE
"DisallowedHost at /" error after deployment

### ISSUE THREAD

**Issue by nickwalkmsft** [Azure-Samples/app-service-web-python-get-started#5]
After deployment, browsing the site gives a yellow error screen with:

DisallowedHost at /
Invalid HTTP_HOST header: '<mysitename>'. You may need to add u'<mysitename>' to ALLOWED_HOSTS.

Modifying ALLOWED_HOSTS in django_get_started/settings.py to { '*' } or { '<mysitename>' } fixes the issue.

Also mentioned in the comments at https://docs.microsoft.com/en-us/azure/app-service-web/app-service-web-get-started-python.

**Comment by cephalin** [comment]
Thanks @nickwalkmsft for showing the fix. Fixed by commit [c407f63](https://github.com/Azure-Samples/app-service-web-python-get-started/commit/c407f633069d80c00dd9f6946b6ac119a259477d)
